# Site settings
baseURL = "https://oliviawang2.netlify.app/"
languageCode = "en-us"
title = "Portfolio Website of Ayush Agrawal"
theme = "forty"

# Enter your tracking code to enable Google Analytics
googleAnalytics = ""

# Enter your disqus shortname to enable comments
disqusShortname = ""

[params]
  # You can use Markdown syntax for urls [text](//url.to/source)
  # To create multi-line text in strings use the """example Text""" format
  #
  # All icons using Fontawesome's icon font. Look at fontawesome.io/icons
  # for more icons. The icons are represented by their corresponding
  # CSS class.

  # Provide your metadata here.
  name = "Ayush Agrawal"
  description = "MFA Student at London Business School"

  # Link custom assets relative to /static
  custom_css = []
  custom_js  = []
  favicon    = "favicon.ico"

  # Just a custom image variable, please define it in .md files for content.
  image = ""

  # 404 error customization
  [params.error404]
    heading = "Page couldn't be found"
    text = "Please visit [this page](/)"

  # Navigation Section
  [params.navigation]
    title = "Ayush Agrawal"
    subtitle = "London Business School"
    menu = "Menu"
    # Optional logo as brand stored in img/
    # logo = "logo.png"

    [[params.navigation.links]]
      name = "Home"
      url = "#"

    [[params.navigation.links]]
      name = "Blogs"
      url = "blogs"

    #[[params.navigation.links]]
      #name = "Generic Blog"
     # url = "blogs/ipsum"

    #[[params.navigation.links]]
     # name = "Elements"
     # url = "elements.html"

    # Add custom links here by uncommenting code below. To remove links just delete
    # the [[params.navigation.links]] map associated with that link. Copy and paste
    # code below if you need more links. Buttons work in the same way.
    # [[params.navigation.links]]
    #    name = "NameOfLink"
    #    url = "UrlOfLink"

    # Button Style 1
   # [[params.navigation.button1]]
    #  name = "Get Started"
    #  url = "blogs"

    # Button Style 2
    # [[params.navigation.button2]]
    #  name = "My Resume"
    #  url = "Ayush_CV_LBS.pdf"


  # Banner section
  [params.banner]
    # To change the background image on the homepage banner, replace 'banner.jpg' in
    # the 'static/img' folder.
    title = "Hi, my name is Ayush Agrawal"
    subtitle = "This site is contains some interesting insights from my Data Analytics class at LBS"
    buttonText = "INSIGHTS" 


  # Tiles Section
  [params.tiles]
    enable = true
    # Display your showcases here.
    
    [[params.tiles.showcase]]
      title = "Cycles!"
      subtitle = "Analysis of TFL Bike Data"
      image = "alpha.jpg"
      url = "blogs/blog1"

    [[params.tiles.showcase]]
      title = "Movies!"
      subtitle = "Comparing IMDB Data with Spielberg and Burton"
      image = "beta.jpg"
      url = "blogs/blog2" 

    [[params.tiles.showcase]]
      title = "Pay!"
      subtitle = "Case based Analysis of Gender Pay Gap"
      image = "gamma.png"
      url = "blogs/blog3"

    [[params.tiles.showcase]]
      title = "Drink!"
      subtitle = "Analysing Beer Consumption across the world"
      image = "delta.jpg"
      url = "blogs/blog4"

   # [[params.tiles.showcase]]
   #   title = "Consequat"
   #   subtitle = "Ipsum Dolor Sit Amet"
   #  image = "pic05.jpg"
   #    url = "blogs/ipsum"

   # [[params.tiles.showcase]]
   #   title = "Etiam"
   #   subtitle = "Feugiat Amet Tempus"
   #   image = "pic06.jpg"
   #   url = "blogs/ipsum"
    # You can make more showcases by copy and pasting the code above

  [params.blog]
    # All blogs defined in their own files. You can find example blogs
    # at 'exampleSite/content/blogs'. Copy the 'blogs' folder into the 'content' directory
    # at the root of this Hugo site.
    # For more informtion take a look at the README.
    # To add more blogs just copy and paste the code.

  # Section Type Two
  [params.two]
    enable = true
    title = "About Me"
    subtitle = """My name is Ayush Agrawal.
    I am currently studying Masters in Financial Analysis at London Business School. Prior to this, I did my undergraduate from Narsee Monjee College of Commerce and Economics in India, where I headed the Planning Forum Jr. Club. I have also completed two levels of the CFA Program.
    I love working with numbers and learning about various businesses. I am also a passionate reader of human motivations and psychology.
    I have interned in consulting and a start-up and my interests lie in taking beautiful photographs, playing games, and curating music playlists for every mood."""
    buttonText = "My Resume"
    url = "Ayush_CV_LBS.pdf"


  # Contact section
  [params.contact]
    enable = true
    buttonSend = "Send message"
    buttonClear = "Clear"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below and uncomment
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    # formEmail = "example@domain.com"

    # Contact Section
    # You can add multiple emails, phone numbers, or addresses
    # by copying the corresponding map with frontmatter code.
    [[params.contact.email]]
    title = "Email"
    email = "aagrawal.mfa2021@london.edu"

    [[params.contact.phone]]
    title = "Phone"
    phone = "+44 77 377 25097"

    [[params.contact.address]]
    title = "Address"
    street = "London Business School"
    city = "London, NW1 6BS"
    country = "United Kingdom"

  # Footer section
  [params.footer]
    enable = true
    copyright = "Ayush Agrawal | London Business School"

    # Uses font awesome icons
    [[params.footer.social]]
      icon = "fa-twitter"
      url= "https://twitter.com/iamnotmozart"
      label = "Twitter"

    #[[params.footer.social]]
     # icon = "fa-facebook"
     # url= "https://www.facebook.com"
     # label = "Facebook"

    [[params.footer.social]]
      icon = "fa-instagram"
      url= "https://www.instagram.com/this.is.ayushagrawal/"
      label = "Instagram"
    
    [[params.footer.social]]
      icon = "fa-github"
      url= "https://github.com/ayushlbs"
      label = "GitHub"

    [[params.footer.social]]
      icon = "fa-linkedin"
      url= "https://www.linkedin.com/in/ayushagr100/"
      label = "LinkedIn"

  #  [[params.footer.quicklinks]]
  #    text = "Design: "
  #    url= "https://www.html5up.net"
  #    alt = "HTML5 UP"
